/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diseñador;

import conexion.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salaf405
 */
public class busquedaMateria extends javax.swing.JFrame {

        ConexionMySQL mysql;
        Connection cn;
        PreparedStatement pst;
        ResultSet rs;
        DefaultTableModel dtm;
    
    /**
     * Creates new form busquedaMateria
     */
    public busquedaMateria() {
        initComponents();
        setDefaultCloseOperation(0);
        mysql = new  ConexionMySQL();//se llama la clase conexión
        cn = mysql.Conectar();  //creamos un objeto para conectar la base de datos sql
        buscar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtbuscarcod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtbuscarnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbuscarMate = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtvalor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcreditos = new javax.swing.JTextField();
        Jornada = new javax.swing.JLabel();
        txtjor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtcodmat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnommat = new javax.swing.JTextField();
        txtcarr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtbuscarcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarcodActionPerformed(evt);
            }
        });
        txtbuscarcod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarcodKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarcodKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Codigo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Nombre");

        txtbuscarnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarnombreActionPerformed(evt);
            }
        });
        txtbuscarnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarnombreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtbuscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtbuscarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtbuscarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtbuscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jtbuscarMate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbuscarMate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbuscarMateMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbuscarMateMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbuscarMate);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Materia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        txtvalor.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Valor Materia");

        txtcreditos.setEnabled(false);

        Jornada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jornada.setText("Jornada");

        txtjor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Semestre");

        txtsem.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo");

        txtcodmat.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nombre Carrera");

        txtnommat.setEnabled(false);

        txtcarr.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("N Creditos");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Acciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        btneliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btneliminar.setToolTipText("Eliminar");
        btneliminar.setEnabled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        btnsalir.setToolTipText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btneliminar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addGap(18, 18, 18)
                .addComponent(btnsalir)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsalir)
                    .addComponent(btncancelar)
                    .addComponent(btneliminar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 74, Short.MAX_VALUE)
                                .addComponent(txtcodmat, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(txtcreditos))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsem)
                            .addComponent(txtcarr))))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Jornada)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtvalor, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(txtjor, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(txtnommat))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnommat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jornada)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtcodmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtcarr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarcodActionPerformed
        buscarCodigo(txtbuscarcod.getText());
    }//GEN-LAST:event_txtbuscarcodActionPerformed

    private void txtbuscarcodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarcodKeyPressed

    }//GEN-LAST:event_txtbuscarcodKeyPressed

    private void txtbuscarcodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarcodKeyReleased

    }//GEN-LAST:event_txtbuscarcodKeyReleased

    private void jtbuscarMateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbuscarMateMouseClicked
        int cod = jtbuscarMate.getSelectedRow();

        txtcodmat.setText(jtbuscarMate.getValueAt(cod, 1).toString());
        txtnommat.setText(jtbuscarMate.getValueAt(cod, 2).toString());
        txtcreditos.setText(jtbuscarMate.getValueAt(cod, 3).toString());
        txtvalor.setText(jtbuscarMate.getValueAt(cod, 4).toString());
        txtsem.setText(jtbuscarMate.getValueAt(cod, 5).toString());
        txtjor.setText(jtbuscarMate.getValueAt(cod, 6).toString());
        txtcarr.setText(jtbuscarMate.getValueAt(cod, 7).toString());


        btneliminar.setEnabled(true);
        btncancelar.setEnabled(true);
    }//GEN-LAST:event_jtbuscarMateMouseClicked

    private void jtbuscarMateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbuscarMateMousePressed

    }//GEN-LAST:event_jtbuscarMateMousePressed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(txtcodmat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe selecionar una materia");
            btneliminar.setEnabled(false);
            btncancelar.setEnabled(false);
            buscar();
        }
        else{
            ConexionMySQL mysql = new ConexionMySQL();//se llama la clase conexión
            Connection cn = mysql.Conectar(); //creamos un objeto para conectar la base de datos sql

            String mts ="DELETE FROM materia WHERE codmateria = "+txtcodmat.getText();

            try{
                Statement st = cn.createStatement();//Obtiene procedimiento o consulta, sin parametros.
                st.execute(mts); //ejecute la consulta, en este caso que elimine.
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            btneliminar.setEnabled(false);
            btncancelar.setEnabled(false);
                    txtbuscarcod.setText("");
        txtbuscarnombre.setText("");
        txtcodmat.setText("");
        txtnommat.setText("");
        txtcreditos.setText("");
        txtvalor.setText("");
        txtsem.setText("");
        txtjor.setText("");
        txtcarr.setText("");
            buscar();
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtbuscarcod.setText("");
        txtbuscarnombre.setText("");
        txtcodmat.setText("");
        txtnommat.setText("");
        txtcreditos.setText("");
        txtvalor.setText("");
        txtsem.setText("");
        txtjor.setText("");
        txtcarr.setText("");
        btneliminar.setEnabled(false);
        btncancelar.setEnabled(false);
        buscar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtbuscarnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarnombreKeyPressed

    }//GEN-LAST:event_txtbuscarnombreKeyPressed

    private void txtbuscarnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarnombreActionPerformed
        buscarNombre(txtbuscarnombre.getText());
    }//GEN-LAST:event_txtbuscarnombreActionPerformed

    
    public void buscar(){
        String titulos[] = {"N°", "Codigo", "Nombre", "N° Creditos", "Valor Materia",
            "Semestre", "Jornada", "Carrera"};
        String filas[] = new String[8];
        String sSQL="";
        sSQL="SELECT * FROM materia";
        dtm = new DefaultTableModel(null, titulos);
        try{
            pst = cn.prepareStatement(sSQL);
            rs = pst.executeQuery(); 
            int c = 1;
            while (rs.next()){
                filas[0] = String.valueOf(c)+"°";
                filas[1] = rs.getString(1);
                filas[2] = rs.getString(2);
                filas[3] = rs.getString(3);
                filas[4] = rs.getString(4);
                filas[5] = rs.getString(5);
                filas[6] = rs.getString(6);
                filas[7] = rs.getString(7);
                dtm.addRow(filas);
                c ++;
            }     
            jtbuscarMate.setModel(dtm);
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }
    
    
     public void buscarNombre(String condicion){
        String titulos[] = {"N°", "Codigo", "Nombre", "N° Creditos", "Valor Materia",
            "Semestre", "Jornada", "Carrera"};
        String filas[] = new String[8];
        String sSQL="";
        sSQL="SELECT * FROM materia WHERE nommateria LIKE '"+condicion+"%'";
        dtm = new DefaultTableModel(null, titulos);
        try{
            pst = cn.prepareStatement(sSQL);
            rs = pst.executeQuery(); 
            int c = 1;
            while (rs.next()){
                filas[0] = String.valueOf(c)+"°";
                filas[1] = rs.getString(1);
                filas[2] = rs.getString(2);
                filas[3] = rs.getString(3);
                filas[4] = rs.getString(4);
                filas[5] = rs.getString(5);
                filas[6] = rs.getString(6);
                filas[7] = rs.getString(7);
                dtm.addRow(filas);
                c ++;
            }     
            jtbuscarMate.setModel(dtm);
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }
     
     
     public void buscarCodigo(String condicion){
        String titulos[] = {"N°", "Codigo", "Nombre", "N° Creditos", "Valor Materia",
            "Semestre", "Jornada", "Carrera"};
        String filas[] = new String[8];
        String sSQL="";
        sSQL="SELECT * FROM materia WHERE codmateria LIKE '%"+condicion+"%'";
        dtm = new DefaultTableModel(null, titulos);
        try{
            pst = cn.prepareStatement(sSQL);
            rs = pst.executeQuery(); 
            int c = 1;
            while (rs.next()){
                filas[0] = String.valueOf(c)+"°";
                filas[1] = rs.getString(1);
                filas[2] = rs.getString(2);
                filas[3] = rs.getString(3);
                filas[4] = rs.getString(4);
                filas[5] = rs.getString(5);
                filas[6] = rs.getString(6);
                filas[7] = rs.getString(7);
                dtm.addRow(filas);
                c ++;
            }     
            jtbuscarMate.setModel(dtm);
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedaMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new busquedaMateria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jornada;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbuscarMate;
    private javax.swing.JTextField txtbuscarcod;
    private javax.swing.JTextField txtbuscarnombre;
    private javax.swing.JTextField txtcarr;
    private javax.swing.JTextField txtcodmat;
    private javax.swing.JTextField txtcreditos;
    private javax.swing.JTextField txtjor;
    private javax.swing.JTextField txtnommat;
    private javax.swing.JTextField txtsem;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
